### PR TITLE
trigger onChange upon changed data

### PR DESCRIPTION
**Pull request by pd46**
The current browser-sync-client changes the value of an input field correctly. But as the current logic just changes the value without triggering an onChange-event there is no chance of reacting to these changes within the other synced clients. That's why e.g. the model of an angular-js application isn't updated appropriately. The changes wihtin my pull request work but break the test suite. Unfortunately I don't really know why my additions break the code. It would be really kind of you to look at my code and merge it if it is helpful or add a more appropriate fix for this problem.

Thanks a lot.

### CODE REVIEW

**Comment by qrohlf** [comment]
+1 to getting this fixed - would make browserSync way more helpful for debugging my React app. 

Also, for some reason the Travis "Details" link to the broken build here is incorrect. The correct URL is https://travis-ci.org/BrowserSync/browser-sync-client/builds/29829380.

**Comment by seriallos** [comment]
Another vote for desire to have this!

**Comment by jschr** [comment]
+1 for the same reasons mentioned

**Comment by markusv** [comment]
Is this going to be implemented?

**Comment by fterrier** [comment]
this would be nice +1

**Pull request closed without merging**
