### PR TITLE
Page blinking on styles reload is fixed.

### PR DESCRIPTION
**Pull request by dangreen**
| Before | After|
|:------:|:------:|
|before|after|

### CODE REVIEW

**Comment by shakyShane** [comment]
Works great, thanks very much :)

**Comment by shakyShane** [comment]
Thanks!

You have been invited to the Browsersync org (which means you'll full write access to all repos)

Please continue to submit PRs for code changes & be sure to review the guidelines. https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-submitting-a-pull-request

Any questions, just ask :)

**Comment by dangreen** [comment]
@shakyShane How soon BrowserSync will release with this changes?

**Comment by shakyShane** [comment]
@dangreen today :)

**Comment by shakyShane** [comment]
@dangreen browser-sync@2.18.9 :)

**Comment by shakyShane** [comment]
@dangreen I had to revert this - It caused problems for my colleagues, and also produced this issue https://github.com/BrowserSync/browser-sync/issues/1379#issuecomment-302902798

We'll need to come up with some good enough tests before landing again, possible e2e now that chrome has headless :)

**Pull request merged**
