### PR TITLE
Implemented more events (keyboard/mouse) & contenteditable synching.

### PR DESCRIPTION
**Pull request by nitinsurana**
Added keydown, keypress, mouseup, mousedown
Modified click to consider special case for SELECT tags and thus select the value.
Added contenteditable input event.

If the pull-request gets accepted then docs have to be updated about these new events and default-config.js in browser-sync will also need to be updated for ghostMode & clientEvents.

### CODE REVIEW

**Comment by shakyShane** [comment]
@nitinsurana sorry for the delay on this, as you may be aware I'm still in the process of a rewrite for Browsersync V3 - when I move to this client lib I will incorporate these changes.

**Comment by nitinsurana** [comment]
ok, thanks for replying.

**Comment by jsguy** [comment]
Hey @shakyShane,

I'm also in need of better event support, are we in a state so that it would be useful to submit a fix?

I see that you have this branch:

https://github.com/BrowserSync/browser-sync-client/tree/bs3

Is that for Browser sync 3?

I have some fixes, which makes it work quite a bit better with with our site, it would be nice to be able to submit them.

-- jsguy

**Comment by jsguy** [comment]
Hi @nitinsurana,

 I've absorbed your changes, plus added (pretty good) touch events and  changed to use an xpath selector for  elements, instead of the "index" (which breaks in some cases) - for the sake of simplicity for @shakyShane, should we drop this pull request and use mine instead, as it includes all your changes anyway?
Here is my code:

https://github.com/jsguy/browser-sync-client

Let me know what you think.

**Comment by shakyShane** [comment]
@jsguy - nice work, I will do some testing with it and see how it looks, thanks very much :)

**Comment by jsguy** [comment]
@shakyShane ok - one thing to note - as you know, you cannot trigger a ":hover" event by javascript, so I've also added support in a slightly outside-the-box way - it works by:

* On mouseover adding a classname ("browser-sync-hover") to the element
* Adding styles dynamically to include this classname and appropriate styles
* Onmouseout, remove the classname

It works pretty well in my testing so far - and enables us to perform much more detailed testing for some of our widgets and components.

**Comment by jsguy** [comment]
Any updates on this? Should I make a separate pull request?

**Pull request closed without merging**
